name: proft
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  fl_chart: ^0.71.0
  video_player: ^2.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  table_calendar: ^3.2.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  share_plus: ^11.0.0
  flutter_time_picker_spinner: ^2.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.3.1

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.70.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  
flutter:
  assets:
     - assets/

      

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/tahadi.png"
  adaptive_icon_background: "0xFFF5B905" # خلفية الأيقونة (يمكنك تغييرها)
  adaptive_icon_foreground: "assets/tahadi.png"

dependency_overrides:
  fl_chart: ^0.71.0  # أو 0.70.2 حسب ما تفضله
